# Generated by Django 5.2.4 on 2025-07-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/images/'),
        ),
    ]
