# Generated by Django 5.2.1 on 2025-07-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0005_remove_article_created_at_remove_article_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='External image URL (if no uploaded image)', null=True),
        ),
    ]
