# Generated by Django 5.2.1 on 2025-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0007_remove_article_featured_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_url',
            field=models.URLField(blank=True, help_text='Alternative to uploading an image file'),
        ),
    ]
