# Generated by Django 5.2.1 on 2025-07-28 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_article_featured_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='featured_image_url',
        ),
    ]
