# Generated by Django 5.2.4 on 2025-07-28 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing_images/')),
                ('link', models.URLField(blank=True)),
                ('section', models.CharField(choices=[('news', 'News'), ('sports', 'Sports'), ('events', 'Events')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Landing Page Feature',
                'verbose_name_plural': 'Landing Page Features',
                'ordering': ['priority'],
            },
        ),
    ]
